// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/factory/annotation

package sync

import (
	"github.com/expgo/factory"
)

func init() {
	factory.Factory[Mutex](NewMutex).CheckValid()
	factory.Factory[Once](NewOnce).CheckValid()
	factory.Factory[RWMutex](NewRWMutex).CheckValid()
	factory.Factory[WaitGroup](NewWaitGroup).CheckValid()
}
